require: rubocop-rspec
AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
RSpec/NestedGroups:
  Max: 5
RSpec/MessageSpies:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/AnyInstance:
  Enabled: false
RSpec/VerifiedDoubleReference:
  Enabled: false
